### ISSUE TITLE
Active Project?

### ISSUE THREAD

**Issue by thomasfr** [systemd/node-systemd#2]
Hi,
i really like to use direct logging to journald so i would really like to use node-systemd. Therefore i wanted to know of any known bugs or missing implementations / bindings?
Are you using this yourself somewhere?
If i can help you with testing and so on let me know.
Kind regards

**Comment by marktheunissen** [comment]
It's active in the sense that pull requests will be merged. No known issues but the code is really simple. I believe Pantheon is using this is production, don't know who else.

**Comment by nstielau** [comment]
@thomasfr We're using this.  Works for us.

**Comment by thomasfr** [comment]
Thanks!
