### ISSUE TITLE
be more defensive about non-string metadata passed to journal.send()

### ISSUE THREAD

**Issue by joemiller** [systemd/node-systemd#9]
It is easy to craft a log message that causes the underlying winston/journal lib to throw an error. It is also easy to miss these issues because a common winston pattern seems to be to ignore errors (this is provided as an option in the winston init method)

https://github.com/systemd/node-systemd/blob/master/lib/log_journald.js#L54-L56

This will throw because `data` is an integer and not a string:

```
    log.error("Error with request: #{e}", {'path': path, 'method': method, 'data': 1})
```

Can we be more defensive and try to convert non-string to string? If so, is `JSON.stringify(data)` the best way to do this?

**Comment by marktheunissen** [comment]
Sounds good, PR is ready.

**Comment by marktheunissen** [comment]
What is the parameter that can be passed to Winston to make it extra strict about errors? I want to put that in test.js

**Comment by joemiller** [comment]
not sure exactly, but maybe this `exit on error` setting:
https://github.com/flatiron/winston/blob/master/README.md#to-exit-or-not-to-exit
